### PR TITLE
Fixes multibyte utf8 conversion

### LINKED ISSUE #23: 3D character in body
Hi,

I have used your sample code to get emails from an inbox. But, the `body` has `3D` characters all over the markup, hence the mail not rendering properly.

e.g: *`<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3DUTF-8">`*

I have already tried `.toString('utf8')`, but makes no difference.

Any ideas?

### PR DESCRIPTION
**Pull request by kalle-manninen**
Fixes #23 3D character in body.

Fix is based on this:
https://github.com/mscdex/node-imap/issues/319#issuecomment-26799708

Fixes problem with non US ascii characters, like Ä, Ö, Å.

### CODE REVIEW

**Comment by chadxz** [comment]
Hey @kalle-manninen, thank you for taking a stab at this and submitting a PR, I really appreciate it!

Because there are no tests here, it is difficult for me to tell that this actually does what we think. What all scenarios did you test? Do you happen to know if this would be considered a breaking change?

**Comment by kalle-manninen** [comment]
Hi, 
I tested it by changing one test you have to get message's body.
In email body I used non US ascii characters like (Ä, Ö, Å). 
The fix shouldn't be a breaking change.

**Comment by chadxz** [comment]
what happens when you have =foo as text in the email body? does that get converted too?

**Comment by kalle-manninen** [comment]
I finally had time to add unit tests. :) It checks those conversions.

**Comment by chadxz** [comment]
It's great that you put some unit tests in for your function. That really helps a lot.

I am primarily concerned that the regex is too general. This PR is *always* performing this conversion regardless of the encoding and charset of the body, which seems like it could cause other problems. I would not want to inadvertently be replacing sequences of characters that are not quoted-printable multi-byte characters but instead something that was typed and intended to be a part of the body as-is.

Would it be possible for you to provide a full example of an email where this is needed, so we can inspect the full body and metadata of the message to better understand the problem?

**Comment by kalle-manninen** [comment]
Now I got it working without doing that change to your code. Gmail seems to encode non US ascii characters.
I can do conversion in my own application.

**Pull request closed without merging**
