### PR TITLE
use iconv-lite to handle 8BIT messages

### PR DESCRIPTION
**Pull request by bvschwartz**
This change allows utf-8 and latin-1 messages to be decoded.

### CODE REVIEW

**Comment by chadxz** [comment]
Node.js Buffer.prototype.toString natively supports converting a buffer to a string using utf-8 encoding. 

https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end
https://nodejs.org/api/buffer.html#buffer_buffers_and_character_encodings

Is there a specific need for the iconv-lite library in this case?

**Comment by bvschwartz** [comment]
Some of the email messages I was processing were latin-1 and node doesn't handle those.

**Comment by chadxz** [comment]
ah okay, that makes sense

**Comment by chadxz** [comment]
published as imap-simple@1.6.0

**Comment by chadxz** [comment]
Thanks @bvschwartz :)

**Pull request merged**
