### PR TITLE
Simple wrapper for imap.getBoxes() method.

### PR DESCRIPTION
**Pull request by AurisAudentis**
Simple wrapper over the getBoxes() function from node-imap.

### CODE REVIEW

**Comment by chadxz** [comment]
Hi @AurisAudentis, thank you for the contribution! This looks to be a straightforward change, and I'd be happy to get it included in the library and cut a new release.

The main thing that I see is that it uses arrow functions, which is syntax that the rest of the library does not currently require.

Would you mind changing the function to not use arrow functions? If we wanted to keep the arrow functions, we'd need to also explicitly declare the javascript / node.js versions that this library supports, and potentially release a major version bump, which is more work. Changing the function to use normal function syntax would be simpler IMO.

**Comment by AurisAudentis** [comment]
@chadxz,
I've now changed the arrow functions to standard anonymous functions, to be in-line with the rest of the library.
I had diverged from this standard because the ES6 promises were already in use, and i had thought it better to then step over fully into ES6 best-practices.

On another topic, it might be advisable to wait a little bit longer before releasing a new version; I have some use-cases I will need to develop for my own project. Some of those might as well also be available in this library, others might not; Either way, I'm inclined to share these features with this library as well.

**Comment by chadxz** [comment]
I agree with you, I just don't spend any time maintaining this library and don't want to have to dig into it any more than necessary right now.

**Comment by chadxz** [comment]
I will try to give this a full review tonight or tomorrow, merge it and cut a new release.

**Comment by chadxz** [comment]
Published as imap-simple@4.1.0

**Comment by AurisAudentis** [comment]
How would i go about updating the @types/ file for this package?

**Comment by chadxz** [comment]
You'd need to submit a PR to https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by AurisAudentis** [comment]
Ok, thanks.

**Pull request merged**
